services:
  postgres:
    image: postgres:16
    container_name: ecifit-db
    environment:
      POSTGRES_DB: ecifit
      POSTGRES_USER: ecifit
      POSTGRES_PASSWORD: ecifit
    ports:
      - "5432:5432"
    volumes:
      - ecifit-data:/var/lib/postgresql/data

volumes:
  ecifit-data: